export const GET_FORUM_DATA = "GET_FORUM_DATA";
export const GET_FORUM_DATA_FAILURE = "GET_FORUM_DATA_FAILURE";
export const GET_FORUM_DATA_SUCCESS = "GET_FORUM_DATA_SUCCESS";

export const GET_SINGLE_QUESTION = "GET_SINGLE_QUESTION";
export const GET_SINGLE_QUESTION_FAILURE = "GET_SINGLE_QUESTION_FAILURE";
export const GET_SINGLE_QUESTION_SUCCESS = "GET_SINGLE_QUESTION_SUCCESS";